apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-frontend-deployment
  labels:
    app: gitops-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-frontend
  template:
    metadata:
      labels:
        app: gitops-frontend
    spec:
      containers:
      - name: frontend-ui
        image: karthikparnandi/enterprise-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-frontend-service
spec:
  selector:
    app: gitops-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer # Exposes the frontend to the public internet using a cloud load balancer